package com.jjc.mybatis.domain;

import com.jjc.mybatis.core.SexEnum;

import java.io.Serializable;
import java.util.List;

public class Employee implements Serializable {
    private static final long serialVersionUID = -3715606576686056353L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.real_name
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     */
    private SexEnum sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mobile
     */
    private String mobile;

    private WorkCard workCard;
    private List<EmployeeTask> tasks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.real_name
     *
     * @return the value of employee.real_name
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.real_name
     *
     * @param realName the value for employee.real_name
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    public SexEnum getSex() {
        return sex;
    }

    public void setSex(SexEnum sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mobile
     *
     * @return the value of employee.mobile
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mobile
     *
     * @param mobile the value for employee.mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    public WorkCard getWorkCard() {
        return workCard;
    }

    public void setWorkCard(WorkCard workCard) {
        this.workCard = workCard;
    }

    public List<EmployeeTask> getTasks() {
        return tasks;
    }

    public void setTasks(List<EmployeeTask> tasks) {
        this.tasks = tasks;
    }
}