package com.jjc.mybatis.domain;

import java.io.Serializable;

public class EmployeeTask implements Serializable {
    private static final long serialVersionUID = 7511790696683238984L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_task.id
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_task.emp_id
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_task.task_id
     */
    private Integer taskId;

    private Task task;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_task.note
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_task.id
     *
     * @return the value of employee_task.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_task.id
     *
     * @param id the value for employee_task.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_task.emp_id
     *
     * @return the value of employee_task.emp_id
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_task.emp_id
     *
     * @param empId the value for employee_task.emp_id
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_task.task_id
     *
     * @return the value of employee_task.task_id
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_task.task_id
     *
     * @param taskId the value for employee_task.task_id
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public Task getTask() {
        return task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_task.note
     *
     * @return the value of employee_task.note
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_task.note
     *
     * @param note the value for employee_task.note
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}