package com.jjc.mybatis.mapper;
import org.apache.ibatis.annotations.Param;

import com.jjc.mybatis.domain.EmployeeTask;
import java.util.List;

public interface EmployeeTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_task
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_task
     */
    int insert(EmployeeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_task
     */
    EmployeeTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_task
     */
    java.util.List<com.jjc.mybatis.domain.EmployeeTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_task
     */
    int updateByPrimaryKey(EmployeeTask record);

    List<EmployeeTask> findByEmpId(@Param("empId")Integer empId);

}