package com.jjc.mybatis.mapper;

import com.jjc.mybatis.domain.Employee;

import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     */
    int updateByPrimaryKey(Employee record);
}