package com.jjc.mybatis.mapper;

import com.jjc.mybatis.domain.Task;
import java.util.List;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     */
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     */
    java.util.List<com.jjc.mybatis.domain.Task> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     */
    int updateByPrimaryKey(Task record);
}