package com.jjc.mybatis.mapper;

import com.jjc.mybatis.domain.WorkCard;

import org.apache.ibatis.annotations.Param;

public interface WorkCardMapper {

    WorkCard selectById(@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_card
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_card
     */
    int insert(WorkCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_card
     */
    int insertSelective(WorkCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_card
     */
    int updateByPrimaryKeySelective(WorkCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_card
     */
    int updateByPrimaryKey(WorkCard record);
}